#!/bin/bash
set -x

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
then
    mkdir -p $OPENSHIFT_DATA_DIR/logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-3.5 ]
then
    wget -P $OPENSHIFT_DATA_DIR https://services.gradle.org/distributions/gradle-3.5-bin.zip
    cd $OPENSHIFT_DATA_DIR
    mkdir  gradle-3.5
    mkdir  gradle-3.5/bin
    unzip $OPENSHIFT_DATA_DIR/gradle-3.5-bin.zip

    rm -f $OPENSHIFT_DATA_DIR/gradle-3.5-bin.zip
fi
chmod +x $OPENSHIFT_DATA_DIR/gradle-3.5/bin/gradle
#if [ ! -d jdk1.8.0_05 ]; then
#  wget -P $OPENSHIFT_DATA_DIR --no-check-certificate --no-cookies --header "Cookie:    oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
#  tar -zxf $OPENSHIFT_DATA_DIR/jdk-8u5-linux-x64.tar.gz
#fi

#export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
#export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0

export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$GRADLE_HOME:$PATH

cd $OPENSHIFT_REPO_DIR

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin

gradle clean build