#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
then
    mkdir -p $OPENSHIFT_DATA_DIR/logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-3.5 ]
then
    wget -P $OPENSHIFT_DATA_DIR https://services.gradle.org/distributions/gradle-3.5-bin.zip
    unzip -j gradle-3.5-bin.zip
    rm -f $OPENSHIFT_DATA_DIR/gradle-3.5-bin.zip
fi

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$GRADLE_HOME:$PATH

cd $OPENSHIFT_REPO_DIR

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin
$GRADLE_USER_HOME/gradle clean build
