#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
then
    mkdir -p $OPENSHIFT_DATA_DIR/logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-3.5 ]
then
    wget -P $OPENSHIFT_DATA_DIR https://services.gradle.org/distributions/gradle-3.5-bin.zip
    unzip -j gradle-3.5-bin.zip
    rm -f $OPENSHIFT_DATA_DIR/gradle-3.5-bin.zip
fi
#    tar xvf $OPENSHIFT_DATA_DIR/REL*.tar.gz --directory $OPENSHIFT_DATA_DIR
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin
export PATH=$GRADLE_HOME:$PATH

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin

cd $OPENSHIFT_REPO_DIR
nohup java -Xms384m -Xmx2g -jar build/libs/VehiclyManager-1.0.0.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift &
