#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

#export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
#export PATH=$JAVA_HOME/bin:$PATH

#Download Java8 If not already installed
#if [ ! -d jdk1.8.0_05 ]; then
#  wget --no-check-certificate --no-cookies --header "Cookie:    oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
#  tar -zxf jdk-8u5-linux-x64.tar.gz
#fi

#export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
#export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
then
    mkdir -p $OPENSHIFT_DATA_DIR/logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-3.5 ]
then
    wget -P $OPENSHIFT_DATA_DIR https://services.gradle.org/distributions/gradle-3.5-bin.zip
    sudo su unzip -j $OPENSHIFT_DATA_DIR/gradle-3.5-bin.zip
    rm -f $OPENSHIFT_DATA_DIR/gradle-3.5-bin.zip
fi
#if [ ! -d jdk1.8.0_05 ]; then
#  wget $OPENSHIFT_DATA_DIR --no-check-certificate --no-cookies --header "Cookie:    oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
#  tar -zxf $OPENSHIFT_DATA_DIR/jdk-8u5-linux-x64.tar.gz
#fi

#export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
#export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
#export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-3.5/bin
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$GRADLE_HOME:$PATH
cd $OPENSHIFT_REPO_DIR
ls
chmod +x $OPENSHIFT_REPO_DIR/build/libs/repo-1.0.0.jar
nohup java -Xms384m -Xmx2g -jar $OPENSHIFT_REPO_DIR/build/libs/repo-1.0.0.jar  --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift &
